### ISSUE TITLE
Splunk on-prem issues

### ISSUE THREAD

**Issue by PJ1288** [Sam-Martin/PagerDuty2Splunk#1]
Our Splunk infra is on-prem. Will this tool still work ? I tried using our heavy forwarder hostname but it's giving me this error:
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by Sam-Martin** [comment]
Hi @PJ1288 ,
I haven't looked at this code since I wrote it over four years ago and without any tests written for it (oops) I think it's pretty unmaintainable, especially as I no longer have access to a Splunk instance to test it with.

From what I remember, I tested it against a hosted version of Splunk that they provided me with, rather than an on-prem versions, and, IIRC there were some pretty gnarly differences between it and the on-prem version at the time (as I think the cloud managed version was pretty new).

If you manage to get this code working for you, or want to adopt the Repo, let me know and I'll give you access to update it!

**Comment by PJ1288** [comment]
Hi @Sam-Martin,

Thank you for your reply. I got it working last week. We have our own on-prem Splunk infrastructure and have been looking at options on how to bring in PagerDuty logs in Splunk. I ended up modifying your code a little bit and running it as a cronjob every morning since  it does not pull data in real time. It's working out great so far. Thank you for writing it up.

And yes, if you are looking for an owner, please feel free to give me permissions. I plan to continue working on this !!

Again thank you for your script. It handled most of what I was looking for. 

-Prachi

**Comment by Sam-Martin** [comment]
Glad to hear it!
I've sent you an invite to collaborate on the repository, should give you everything you need!
I'll add you as a PyPi collaborator too on https://pypi.org/project/pagerduty2splunk/ I just need your PyPi username!

**Comment by PJ1288** [comment]
Thanks @Sam-Martin 
My PyPi username is PJ1288. 
Thanks !!

**Comment by Sam-Martin** [comment]
You are now added as an owner on pypi!

**Comment by PJ1288** [comment]
Thanks @Sam-Martin
